FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# corodronesservice

Описание REST API проекта "МетеоБАС", предназначенного для демонстрации метеообеспечения БАС, 
отслеживания БПЛА при перелетах "Погорелое-Городище - Алфельево".

## Положения объектов от ДЕЦИМА [/objects/decima]

### Получить список с объектами от ДЕЦИМА [GET]

+ Response 200 (application/json; charset=UTF-8)

        {
            "items": [
                    {
                        "flightNumber": "NUMBER1",
                        "latitude": 61.6988,
                        "longitude": 72.177946666667,
                        "altitude": 14.02448,
                        "velocity": 0,
                        "time": 1589864781
                    },
                    {
                        "flightNumber": "NUMBER2",
                        "latitude": 51.939325,
                        "longitude": 104.7471,
                        "altitude": 135.36672,
                        "velocity": 1.4388787072,
                        "time": 1589951264
                    }
                ],
            "count": 2
        }

+ Response 204

+ Response 404


## Траектории объектов от ДЕЦИМА [/trajectory/decima{?id}]

### Получить список траекторий объектов от ДЕЦИМА [GET]


+ Response 200 (application/json; charset=UTF-8)

        {
            "items": [
                {
                    "id": "NUMBER1",
                    "data": [
                        {
                            "time": 1589864384,
                            "latitude": 61.698871666667,
                            "longitude": 72.178053333333,
                            "altitude": 12.80496
                        },
                        {
                            "time": 1589864781,
                            "latitude": 61.6988,
                            "longitude": 72.177946666667,
                            "altitude": 14.02448
                        }
                    ]
                }
            ],
            "count": 1
        }
            

+ Response 204