FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# corodronesservice

Описание REST API проекта "МетеоБАС", предназначенного для демонстрации метеообеспечения БАС, 
отслеживания БПЛА при перелетах "Погорелое-Городище - Алфельево".

## Положения объектов от ДЕЦИМА [/objects/decima]

### Получить список с объектами от ДЕЦИМА [GET]

+ Response 200 (application/json; charset=UTF-8)

        {
            "items": [
                    {
                        "flightNumber": "NUMBER1",
                        "latitude": 61.6988,
                        "longitude": 72.177946666667,
                        "altitude": 14.02448,
                        "velocity": 0,
                        "time": 1589864781
                    },
                    {
                        "flightNumber": "NUMBER2",
                        "latitude": 51.939325,
                        "longitude": 104.7471,
                        "altitude": 135.36672,
                        "velocity": 1.4388787072,
                        "time": 1589951264
                    }
                ],
            "count": 2
        }

+ Response 204

+ Response 404


## Траектории объектов от ДЕЦИМА [/trajectory/decima{?id}]

+ Parameters
    + id (optional, String) ... Позывной БПЛА

    
### Получить список траекторий объектов от ДЕЦИМА [GET]

+ Response 200 (application/json; charset=UTF-8)

        {
            "items": [
                {
                    "id": "NUMBER1",
                    "data": [
                        {
                            "time": 1589864384,
                            "latitude": 61.698871666667,
                            "longitude": 72.178053333333,
                            "altitude": 12.80496
                        },
                        {
                            "time": 1589864781,
                            "latitude": 61.6988,
                            "longitude": 72.177946666667,
                            "altitude": 14.02448
                        }
                    ]
                }
            ],
            "count": 1
        }
            

+ Response 204

+ Response 404

## Запланированные маршруты полета БПЛА [/routes]

### Получить список запланированных маршрутов полета БПЛА [GET]

+ Response 200 (application/json; charset=UTF-8)

        {
            "payloadProfiles": [
                {
                    "name": "CameraEditionExample",
                    "payloadType": "CAMERA",
                    "imageKey": "some_key",
                    "sealed": false,
                    "unremovable": false,
                    "parameters": {
                        "weight": 0.074,
                        "frequency": 0,
                        "power": 0,
                        "trueFocalLength": 0.0028,
                        "sensorWidth": 0.00617,
                        "sensorHeight": 0.00455,
                        "sensorHorizontalPixels": 4000,
                        "sensorVerticalPixels": 3000,
                        "minTriggeringInterval": 1
                    }
                }
            ],
            "vehicleProfiles": [
                {
                    "name": "SomeEmulator",
                    "vehicleType": "FIXED_WING",
                    "modelKey": "3dr_aero_m",
                    "imageKey": "3dr_aero_m",
                    "platformCode": "Emulator",
                    "sealed": false,
                    "unremovable": true,
                    "primary": true,
                    "payloadProfiles": [
                        "CameraEditionExample"
                    ],
                    "parameters": {
                        "height": 0.5,
                        "width": 1.8,
                        "length": 1.3,
                        "maxClimbRate": 2,
                        "maxHorizontalSpeed": 25,
                        "maxAltitude": 4000,
                        "maxWaypoints": 120,
                        "maxFlightTime": 2400,
                        "windResistance": 12,
                        "dryTakeoffWeight": 2.65,
                        "maxTakeoffWeight": 4.65,
                        "batteryWeight": 0.65,
                        "chargedBatteryVoltage": 16.8,
                        "dischargedBatteryVoltage": 12.6,
                        "normalBatteryVoltage": 14,
                        "lowBatteryVoltage": 13.3,
                        "lowGpsSatellites": 7,
                        "normalGpsSatellites": 9,
                        "safeDistanceToTerrain": 50,
                        "safeDistanceToObstacle": 100,
                        "waypointAcceptanceRadius": 10,
                        "fenceRadius": 500,
                        "lowTelemetryLevel": 50,
                        "normalTelemetryLevel": 70,
                        "defaultClimbRate": 2,
                        "defaultDescentRate": 1,
                        "glideSlope": 20,
                        "defaultHorizontalSpeed": 15,
                        "landingGroundSpeed": 10,
                        "maxAltitudeAgl": 120,
                        "landingFlareAltitude": null,
                        "landingFlareTime": null,
                        "minLandingPitch": null,
                        "landingFlareDamp": null,
                        "landingApproachAirspeed": null,
                        "landingSpeedWeighting": null,
                        "maxAutoFlightPitch": null,
                        "maxPitch": null,
                        "minThrottle": null,
                        "landingSinkRate": null,
                        "landingRangefinderEnabled": null,
                        "minRangefinderDistance": null,
                        "maxDescentRate": 1,
                        "lowBatteryPowerLevel": 20,
                        "normalBatteryPowerLevel": 50
                    }
                }
            ],
            "vehicles": [
                {
                    "name": "SomeCopter",
                    "vehicleId": 4289872485,
                    "icaoAddress": null,
                    "tailNumber": null,
                    "type": "MULTICOPTER",
                    "altitudeOrigin": null,
                    "platformCode": "SomeCOde",
                    "profile": "SomeProfile",
                    "emulator": false,
                    "serialNumber": "1",
                    "port": "com6",
                    "source": "VSM"
                }
            ],
            "mission": {
                "name": "SomeMission",
                "description": null,
                "creationTime": 1501144514756,
                "routes": [
                    {
                        "name": "SomeRoute",
                        "creationTime": 1501139400000,
                        "scheduledTime": null,
                        "startDelay": null,
                        "vehicleProfile": "SomeEmulator",
                        "altitudeType": "AGL",
                        "trajectoryType": "STRAIGHT",
                        "safeAltitude": 50,
                        "maxAltitude": 120,
                        "initialSpeed": 0,
                        "maxSpeed": 0,
                        "failsafes": {
                            "rcLost": "GO_HOME",
                            "gpsLost": "WAIT",
                            "lowBattery": "LAND",
                            "datalinkLost": "GO_HOME"
                        },
                        "checkAerodromeNfz": true,
                        "checkCustomNfz": true,
                        "segments": [
                            {
                                "type": "TakeOff",
                                "actions": [],
                                "point": {
                                    "latitude": 0.8163853594357775,
                                    "longitude": 0.1456501603260042,
                                    "altitude": 31.054388543823734,
                                    "altitudeType": "AGL"
                                },
                                "parameters": {
                                    "avoidObstacles": true,
                                    "avoidTerrain": true,
                                    "speed": 5
                                }
                            },
                            {
                                "type": "Waypoint",
                                "actions": [],
                                "point": {
                                    "latitude": 0.8163858617141155,
                                    "longitude": 0.14563694689881257,
                                    "altitude": 34.95069231768139,
                                    "altitudeType": "AGL"
                                },
                                "parameters": {
                                    "avoidObstacles": true,
                                    "avoidTerrain": true,
                                    "speed": 5,
                                    "wpTurnType": "STOP_AND_TURN"
                                }
                            },
                            {
                                "type": "Photogrammetry",
                                "actions": [
                                    {
                                        "type": "CameraSeriesByTime",
                                        "interval": null,
                                        "shotsNumber": null,
                                        "startDelay": null,
                                        "autoCalc": true
                                    }
                                ],
                                "polygon": {
                                    "points": [
                                        {
                                            "latitude": 0.8163731961263552,
                                            "longitude": 0.14566000911657936,
                                            "altitude": 0,
                                            "altitudeType": "AGL"
                                        },
                                        {
                                            "latitude": 0.8163681310167368,
                                            "longitude": 0.14567378346675408,
                                            "altitude": 0,
                                            "altitudeType": "AGL"
                                        }
                                    ]
                                },
                                "parameters": {
                                    "actionExecution": "ACTIONS_ON_FORWARD_PASSES",
                                    "altitudeType": "AGL",
                                    "areaScanAllowPartialCalculation": false,
                                    "avoidObstacles": true,
                                    "camera": "CameraEditionExample",
                                    "camTopFacingForward": true,
                                    "directionAngle": 23,
                                    "doubleGrid": false,
                                    "generateAdditionalWaypoints": false,
                                    "groundSampleDistance": 2,
                                    "noActionsAtLastPoint": true,
                                    "overlapForward": 70,
                                    "overlapSide": 60,
                                    "overshoot": null,
                                    "overshootSpeed": null,
                                    "speed": 10,
                                    "tolerance": 1,
                                    "wpTurnType": "SPLINE"
                                }
                            },
                            {
                                "type": "Waypoint",
                                "actions": [],
                                "point": {
                                    "latitude": 0.8163851821720645,
                                    "longitude": 0.14564970906942715,
                                    "altitude": 31.054388543823734,
                                    "altitudeType": "AGL"
                                },
                                "parameters": {
                                    "avoidObstacles": true,
                                    "avoidTerrain": true,
                                    "speed": 5,
                                    "wpTurnType": "SPLINE"
                                }
                            },
                            {
                                "type": "TakeOff",
                                "actions": [],
                                "point": {
                                    "latitude": 0.9797811727471393,
                                    "longitude": 0.6098413504007494,
                                    "altitude": 29.933313882211223,
                                    "altitudeType": "AGL"
                                },
                                "parameters": {
                                    "avoidObstacles": true,
                                    "avoidTerrain": true,
                                    "speed": 5
                                }
                            }
                        ],
                        "takeoffHeight": null
                    }
                ],
                "vehicles": [
                    "SomeCopter1"
                ]
            }
        }

+ Response 404


## Соотнесение номера рейса и названия маршрута [/routes/info]

### Получить таблицу соотнесения номера рейса и названия маршрута [GET]

+ Response 200 (application/json; charset=UTF-8)

        {
            "items": [
                {
                    "flightNumber": "NUMBER1",
                    "route": "ROUTE1"
                },
                {
                    "flightNumber": "NUMBER2",
                    "route": "ROUTE2"
                }
            ],
            "count": 2
        }

+ Response 204

+ Response 404

## Метеопрогноз по маршруту Орловка - Погорелое Городище [/meteo/route]

### Получить метеопрогноз по маршруту Орловка - Погорелое Городище [GET]

+ Response 200 (application/json; charset=UTF-8)

        {
            "count": 4,
            "items": [
                {
                    "date": "20200520T120000",
                    "profile": [
                        {
                            "coordinate": {
                                "latitude": 56.142626,
                                "longitude": 34.987395
                            },
                            "pointName": "R1",
                            "data": [
                                {
                                    "height": 208,
                                    "windSpeed": 4.950497444687018,
                                    "windDirection": 354.85561237566645
                                },
                                {
                                    "height": 308,
                                    "windSpeed": 5.277985753835761,
                                    "windDirection": 353.8218170420122
                                },
                                {
                                    "height": 408,
                                    "windSpeed": 5.821077082199134,
                                    "windDirection": 352.2815782770567
                                },
                                {
                                    "height": 508,
                                    "windSpeed": 6.026392607452602,
                                    "windDirection": 351.16812968623765
                                }
                            ]
                        }
                    ]
                },
                {
                    "date": "20200520T130000",
                    "profile": [
                        {
                            "coordinate": {
                                "latitude": 56.142626,
                                "longitude": 34.987395
                            },
                            "pointName": "R1",
                            "data": [
                                {
                                    "height": 208,
                                    "windSpeed": 4.342540619497339,
                                    "windDirection": 321.7467083907157
                                },
                                {
                                    "height": 308,
                                    "windSpeed": 4.724796619254845,
                                    "windDirection": 320.5038268295551
                                },
                                {
                                    "height": 408,
                                    "windSpeed": 5.365360725085247,
                                    "windDirection": 318.4098801348923
                                },
                                {
                                    "height": 508,
                                    "windSpeed": 5.715554228944973,
                                    "windDirection": 317.054260535659
                                }
                            ]
                        }
                    ]
                }
            ]
        }
+ Response 204

+ Response 404

## Оперативные метеовеличины от метеостанций  [/meteo/stations]

### Получить значения оперативных метеовеличин от метеостанции [GET]

+ Response 200 (application/json; charset=UTF-8)

        {
                "items": [
                {
                    "id": "1",
                    "latitude": 56.1431,
                    "longitude": 34.9897,
                    "humidity": 60,
                    "pressure": 98100,
                    "windSpeed": 7.9,
                    "windAzimuth": 323,
                    "temperature": 10.9,
                    "profile": [
                        {
                            "altitude": 25,
                            "temperature": 8.2
                        },
                        {
                            "altitude": 50,
                            "temperature": 8
                        },
                        {
                            "altitude": 75,
                            "temperature": 7.7
                        },
                        {
                            "altitude": 100,
                            "temperature": 7.5
                        },
                        {
                            "altitude": 150,
                            "temperature": 7
                        },
                        {
                            "altitude": 200,
                            "temperature": 6.5
                        },
                        {
                            "altitude": 250,
                            "temperature": 5.9
                        },
                        {
                            "altitude": 300,
                            "temperature": 5.4
                        },
                        {
                            "altitude": 350,
                            "temperature": 4.9
                        },
                        {
                            "altitude": 400,
                            "temperature": 4.4
                        },
                        {
                            "altitude": 450,
                            "temperature": 3.9
                        },
                        {
                            "altitude": 500,
                            "temperature": 3.2
                        },
                        {
                            "altitude": 550,
                            "temperature": 2.7
                        },
                        {
                            "altitude": 600,
                            "temperature": 2.1
                        },
                        {
                            "altitude": 650,
                            "temperature": 1.6
                        },
                        {
                            "altitude": 700,
                            "temperature": 1.2
                        },
                        {
                            "altitude": 750,
                            "temperature": 0.8
                        },
                        {
                            "altitude": 800,
                            "temperature": 0.5
                        },
                        {
                            "altitude": 850,
                            "temperature": 0.2
                        },
                        {
                            "altitude": 900,
                            "temperature": -0.1
                        },
                        {
                            "altitude": 950,
                            "temperature": -0.3
                        },
                        {
                            "altitude": 1000,
                            "temperature": -0.6
                        }
                    ]
                }
            ],
            "count": 1
        }

+ Response 204

+ Response 404


## Метеопрогноз на 72 часа  [/localforecast{?lat,lon}]

+ Parameters
    + lat (Required, String) ... Широта точки, для которой необходим прогноз
    + lon (Required, String) ... Долгота точки, для которой необходим прогноз

### Получить метеопрогноз для точки на 72 часа [GET]

+ Response 200 (application/json; charset=UTF-8)

        {
            "data": [
                {
                    "time": "20.05.2020T16",
                    "temperature": 9.824,
                    "pressure": 982.501,
                    "windspeed": 7.148466,
                    "winddir": 298.682947,
                    "gusts": 5.71833,
                    "visibility": 24.1349,
                    "clouds": 10,
                    "cloudslow": 4018.8465575145074,
                    "convective": true
                },
                {
                    "time": "20.05.2020T17",
                    "temperature": 10.75,
                    "pressure": 981.671,
                    "windspeed": 9.41756,
                    "winddir": 289.307586,
                    "gusts": 5.81402,
                    "visibility": 16.9949,
                    "clouds": 10,
                    "cloudslow": 3990.8061317447496,
                    "convective": true
                },
                {
                    "time": "21.05.2020T02",
                    "temperature": 2.35,
                    "pressure": 982.034,
                    "windspeed": 7.502719,
                    "winddir": 297.540048,
                    "gusts": 9.61462,
                    "visibility": 24.1348,
                    "clouds": 9,
                    "cloudslow": 6659.139134849063,
                    "convective": false
                },
                {
                    "time": "21.05.2020T03",
                    "temperature": 1.516,
                    "pressure": 982.137,
                    "windspeed": 6.064074,
                    "winddir": 303.06701,
                    "gusts": 8.92638,
                    "visibility": 24.1352,
                    "clouds": 9,
                    "cloudslow": 6658.9939633706745,
                    "convective": false
                },
                {
                    "time": "23.05.2020T16",
                    "temperature": 12.299,
                    "pressure": 996.271,
                    "windspeed": 10.695729,
                    "winddir": 258.009573,
                    "gusts": 6.12361,
                    "visibility": 24.1349,
                    "clouds": 4,
                    "cloudslow": 1302.4178573175864,
                    "convective": false
                }
            ]
        }

+ Response 204

+ Response 404